@startuml ExpeditionProgression

skinparam classAttributeIconSize 0
skinparam classFontSize 11
skinparam groupInheritance 2
hide empty members

title OneBlock Expedition Progression Tree\n(arrows = expedition unlock cost)

class Default <<Cost : 0 / Reward : 1>> {
	Ticks : 25
	ID: entity:Rabbit / Weight : 3
	ID: entity:Chicken / Weight : 3
	ID: Ingredient_Fibre / Weight : 35
	ID: Ingredient_Stick / Weight : 30
	ID: Rubble_Stone / Weight : 25
	ID: Soil_Dirt / Weight : 25
}

class CaveEntry <<Cost : 1 / Reward : 1>> {
	Ticks : 25
	ID: entity:Bat / Weight : 2
	ID: entity:Rat / Weight : 2
	ID: Rubble_Stone / Weight : 35
	ID: Rock_Stone / Weight : 30
	ID: Ore_Copper / Weight : 4
}

class ForestEdge <<Cost : 1 / Reward : 1>> {
	Ticks : 25
	ID: entity:Rabbit / Weight : 4
	ID: entity:Boar / Weight : 2
	ID: entity:Boar_Piglet / Weight : 3
	ID: entity:Fox / Weight : 1
	ID: Ingredient_Stick / Weight : 35
	ID: Wood_Oak_Trunk / Weight : 28
	ID: Plant_Sapling_Oak / Weight : 8
	ID: Plant_Fruit_Apple / Weight : 3
}

class Plain <<Cost : 1 / Reward : 1>> {
	Ticks : 25
	ID: entity:Rabbit / Weight : 4
	ID: entity:Sheep / Weight : 3
	ID: entity:Chicken / Weight : 4
	ID: entity:Antelope / Weight : 1
	ID: Plant_Crop_Carrot_Item / Weight : 16
	ID: Plant_Crop_Corn_Item / Weight : 16
	ID: Plant_Crop_Wheat_Item / Weight : 24
	ID: Ingredient_Fibre / Weight : 30
}

class Cave <<Cost : 2 / Reward : 1>> {
	Ticks : 25
	ID: entity:Rat / Weight : 3
	ID: entity:Bat / Weight : 3
	ID: entity:Spider / Weight : 1
	ID: Rock_Stone / Weight : 35
	ID: Rubble_Stone / Weight : 30
	ID: Ore_Copper / Weight : 5
}

enum RatCave <<Dungeon / Cost : 3 / Reward : 8>> {
	Wave 1 - entity:Rat x 3
	Wave 2 - entity:Rat x 2 + entity:Spider x 1
	Wave 3 - entity:Spider x 2 + entity:Cave_Spider x 1
}

class LowerCave <<Cost : 3 / Reward : 2>> {
	Ticks : 28
	ID: entity:Rat / Weight : 3
	ID: entity:Bat / Weight : 3
	ID: entity:Spider / Weight : 2
	ID: entity:Cave_Spider / Weight : 1
	ID: Rock_Stone / Weight : 35
	ID: Rubble_Stone / Weight : 35
	ID: Ore_Copper / Weight : 7
}

class CopperCave <<Cost : 4 / Reward : 2>> {
	Ticks : 30
	ID: entity:Bat / Weight : 2
	ID: entity:Rat / Weight : 2
	ID: entity:Goblin_Miner / Weight : 1
	ID: Rock_Stone / Weight : 30
	ID: Rubble_Stone / Weight : 25
	ID: Ore_Copper / Weight : 20
	ID: Ore_Iron / Weight : 3
}

enum GobelinGank <<Dungeon / Cost : 5 / Reward : 12>> {
	Wave 1 - entity:Goblin_Scrapper x 2
	Wave 2 - entity:Goblin_Scrapper x 2 + entity:Goblin_Miner x 1
	Wave 3 - entity:Goblin_Scrapper x 3 + entity:Goblin_Miner x 2
}

class IronCave <<Cost : 6 / Reward : 3>> {
	Ticks : 30
	ID: entity:Goblin_Scrapper / Weight : 2
	ID: entity:Goblin_Miner / Weight : 3
	ID: entity:Goblin_Scavenger / Weight : 1
	ID: Rock_Basalt / Weight : 24
	ID: Rubble_Basalt / Weight : 24
	ID: Ore_Iron / Weight : 22
	ID: Ore_Thorium / Weight : 3
}

class SandCave <<Cost : 5 / Reward : 2>> {
	Ticks : 28
	ID: entity:Bat / Weight : 2
	ID: entity:Spider / Weight : 2
	ID: entity:Cactee / Weight : 1
	ID: Block_Sand / Weight : 25
	ID: Rock_Sandstone / Weight : 28
	ID: Rubble_Sandstone / Weight : 24
	ID: Ore_Gold / Weight : 3
}

class GoldCave <<Cost : 7 / Reward : 3>> {
	Ticks : 30
	ID: entity:Goblin_Scrapper / Weight : 2
	ID: entity:Goblin_Miner / Weight : 2
	ID: entity:Goblin_Thief / Weight : 1
	ID: Rock_Basalt / Weight : 24
	ID: Rubble_Basalt / Weight : 24
	ID: Ore_Gold / Weight : 16
	ID: Rock_Gem_Topaz / Weight : 3
}

class ThoriumCave <<Cost : 8 / Reward : 4>> {
	Ticks : 30
	ID: entity:Goblin_Scrapper / Weight : 2
	ID: entity:Goblin_Miner / Weight : 2
	ID: entity:Goblin_Lobber / Weight : 1
	ID: Rock_Basalt / Weight : 24
	ID: Rubble_Basalt / Weight : 24
	ID: Ore_Thorium / Weight : 18
	ID: Ore_Cobalt / Weight : 3
}

enum GobelinInvasion <<Dungeon / Cost : 9 / Reward : 24>> {
	Wave 1 - entity:Goblin_Scrapper x 3 + entity:Goblin_Miner x 1
	Wave 2 - entity:Goblin_Scrapper x 4 + entity:Goblin_Miner x 2
	Wave 3 - entity:Goblin_Scrapper x 4 + entity:Goblin_Miner x 3
	Wave 4 - entity:Goblin_Scrapper x 6 + entity:Goblin_Miner x 3
}

class SilverCave <<Cost : 9 / Reward : 4>> {
	Ticks : 30
	ID: entity:Goblin_Miner / Weight : 2
	ID: entity:Cave_Spider / Weight : 2
	ID: entity:Goblin_Thief / Weight : 1
	ID: Rock_Shale / Weight : 26
	ID: Rubble_Shale / Weight : 24
	ID: Ore_Silver / Weight : 18
	ID: Rock_Gem_Sapphire / Weight : 3
}

class CobaltCave <<Cost : 10 / Reward : 5>> {
	Ticks : 30
	ID: entity:Goblin_Scrapper / Weight : 2
	ID: entity:Goblin_Miner / Weight : 2
	ID: entity:Goblin_Lobber / Weight : 2
	ID: entity:Goblin_Ogre / Weight : 1
	ID: Rock_Shale / Weight : 24
	ID: Rubble_Shale / Weight : 22
	ID: Ore_Cobalt / Weight : 18
	ID: Ore_Adamantite / Weight : 3
}

class AdamantiteCave <<Cost : 13 / Reward : 6>> {
	Ticks : 30
	ID: entity:Goblin_Scrapper / Weight : 2
	ID: entity:Goblin_Miner / Weight : 2
	ID: entity:Goblin_Lobber / Weight : 2
	ID: entity:Goblin_Ogre / Weight : 1
	ID: Rubble_Shale / Weight : 22
	ID: Rock_Shale / Weight : 22
	ID: Ore_Adamantite / Weight : 18
	ID: Ore_Mithril / Weight : 3
}

class GemCave <<Cost : 11 / Reward : 5>> {
	Ticks : 30
	ID: entity:Cave_Spider / Weight : 2
	ID: entity:Goblin_Thief / Weight : 1
	ID: entity:Earth_Elemental / Weight : 1
	ID: Rubble_Shale / Weight : 22
	ID: Rock_Shale / Weight : 22
	ID: Rock_Gem_Emerald / Weight : 12
	ID: Rock_Gem_Topaz / Weight : 10
	ID: Rock_Gem_Sapphire / Weight : 4
}

class FireCave <<Cost : 14 / Reward : 6>> {
	Ticks : 30
	ID: entity:Zombie_Burnt / Weight : 2
	ID: entity:Emberwulf / Weight : 2
	ID: entity:Burnt_Skeleton_Soldier / Weight : 1
	ID: Rock_Volcanic / Weight : 26
	ID: Rubble_Volcanic / Weight : 24
	ID: Rubble_Volcanic_Medium / Weight : 14
	ID: Ingredient_Fire_Essence / Weight : 8
	ID: Ore_Thorium / Weight : 10
	ID: Ore_Cobalt / Weight : 3
}

class GemDeepCave <<Cost : 15 / Reward : 7>> {
	Ticks : 30
	ID: entity:Cave_Spider / Weight : 2
	ID: entity:Earth_Elemental / Weight : 2
	ID: entity:Earthen_Golem / Weight : 1
	ID: Rock_Shale / Weight : 20
	ID: Rubble_Shale / Weight : 20
	ID: Rock_Gem_Emerald / Weight : 12
	ID: Rock_Gem_Topaz / Weight : 10
	ID: Rock_Gem_Sapphire / Weight : 8
	ID: Rock_Gem_Diamond / Weight : 3
}

class MithrilCave <<Cost : 16 / Reward : 7>> {
	Ticks : 30
	ID: entity:Goblin_Scrapper / Weight : 2
	ID: entity:Goblin_Miner / Weight : 2
	ID: entity:Goblin_Ogre / Weight : 1
	ID: Rock_Ledge_Brick / Weight : 28
	ID: Ore_Mithril / Weight : 18
	ID: Ore_Onyxium / Weight : 3
}

class OnyxiumCave <<Cost : 19 / Reward : 8>> {
	Ticks : 30
	ID: entity:Goblin_Scrapper / Weight : 2
	ID: entity:Goblin_Miner / Weight : 2
	ID: entity:Void_Crawler / Weight : 1
	ID: Rock_Ledge_Brick / Weight : 26
	ID: Ore_Onyxium / Weight : 18
	ID: Ore_Prisma / Weight : 3
}

class PrismaCave <<Cost : 23 / Reward : 10>> {
	Ticks : 30
	ID: entity:Goblin_Scrapper / Weight : 2
	ID: entity:Goblin_Miner / Weight : 2
	ID: entity:Void_Crawler / Weight : 2
	ID: entity:Void_Eye / Weight : 1
	ID: Rock_Volcanic / Weight : 20
	ID: Rubble_Volcanic / Weight : 20
	ID: Ore_Prisma / Weight : 16
	ID: Rock_Gem_Zephyr / Weight : 4
}

class SandCavern <<Cost : 6 / Reward : 3>> {
	Ticks : 30
	ID: entity:Bat / Weight : 2
	ID: entity:Cactee / Weight : 2
	ID: entity:Sandswept_Zombie / Weight : 1
	ID: Rubble_Stone / Weight : 22
	ID: Rock_Stone / Weight : 22
	ID: Rock_Sandstone / Weight : 26
	ID: Rubble_Sandstone / Weight : 24
	ID: Ore_Gold / Weight : 3
}

class Desert <<Cost : 7 / Reward : 3>> {
	Ticks : 25
	ID: entity:Cactee / Weight : 2
	ID: entity:Camel / Weight : 3
	ID: entity:Camel_Calf / Weight : 2
	ID: entity:Sandswept_Zombie / Weight : 1
	ID: Block_Sand / Weight : 32
	ID: Rock_Sandstone / Weight : 24
	ID: Rubble_Sandstone / Weight : 22
	ID: Plant_Cactus_1 / Weight : 16
	ID: Plant_Cactus_Ball_1 / Weight : 10
	ID: Plant_Cactus_Flat_1 / Weight : 10
	ID: Ore_Gold / Weight : 3
}

class ForestEntry <<Cost : 2 / Reward : 1>> {
	Ticks : 25
	ID: entity:Boar / Weight : 3
	ID: entity:Boar_Piglet / Weight : 4
	ID: entity:Pigeon / Weight : 4
	ID: entity:Fox / Weight : 2
	ID: entity:Wolf / Weight : 1
	ID: Ingredient_Stick / Weight : 28
	ID: Wood_Oak_Trunk / Weight : 24
	ID: Wood_Beech_Trunk / Weight : 16
	ID: Wood_Ash_Trunk / Weight : 10
	ID: Plant_Sapling_Oak / Weight : 8
	ID: Plant_Sapling_Beech / Weight : 6
	ID: Plant_Sapling_Ash / Weight : 5
	ID: Plant_Crop_Mushroom_Cap_Brown / Weight : 8
	ID: Plant_Crop_Mushroom_Common_Brown / Weight : 8
	ID: Plant_Crop_Mushroom_Shelve_Brown / Weight : 5
}

class Pond <<Cost : 3 / Reward : 2>> {
	Ticks : 25
	ID: entity:Frog / Weight : 4
	ID: entity:Duck / Weight : 4
	ID: entity:Bluegill / Weight : 4
	ID: Fish_Bluegill_Item / Weight : 20
	ID: Plant_Moss_Block_Green / Weight : 18
	ID: Plant_Moss_Rug_Green / Weight : 18
	ID: Soil_Clay_Blue / Weight : 14
	ID: Soil_Dirt / Weight : 18
}

class River <<Cost : 4 / Reward : 2>> {
	Ticks : 25
	ID: entity:Frog / Weight : 3
	ID: entity:Duck / Weight : 3
	ID: entity:Bluegill / Weight : 4
	ID: entity:Crab / Weight : 1
	ID: Fish_Bluegill_Item / Weight : 20
	ID: Rubble_Stone / Weight : 18
	ID: Rock_Stone / Weight : 18
	ID: Soil_Clay_Blue / Weight : 14
	ID: Plant_Moss_Green / Weight : 16
}

class Lake <<Cost : 5 / Reward : 2>> {
	Ticks : 28
	ID: entity:Frog / Weight : 3
	ID: entity:Duck / Weight : 3
	ID: entity:Bluegill / Weight : 4
	ID: entity:Crocodile / Weight : 1
	ID: Fish_Bluegill_Item / Weight : 22
	ID: Plant_Moss_Block_Green / Weight : 18
	ID: Plant_Moss_Rug_Green / Weight : 18
	ID: Soil_Clay_Blue / Weight : 16
	ID: Rock_Gem_Sapphire / Weight : 3
}

class Sea <<Cost : 7 / Reward : 3>> {
	Ticks : 30
	ID: entity:Crab / Weight : 4
	ID: entity:Bluegill / Weight : 3
	ID: entity:Skeleton_Pirate_Striker / Weight : 2
	ID: entity:Skeleton_Pirate_Gunner / Weight : 1
	ID: Fish_Whale_Humpback_Item / Weight : 2
	ID: Rock_Aqua_Brick / Weight : 20
	ID: Rock_Aqua_Brick_Smooth / Weight : 18
	ID: Plant_Coral_Block_Yellow / Weight : 14
	ID: Plant_Coral_Bush_Yellow / Weight : 14
	ID: Plant_Coral_Model_Yellow / Weight : 10
	ID: Rock_Gem_Sapphire / Weight : 3
}

enum PirateShipwreck <<Dungeon / Cost : 10 / Reward : 30>> {
	Wave 1 - entity:Skeleton_Pirate_Striker x 4
	Wave 2 - entity:Skeleton_Pirate_Striker x 3 + entity:Skeleton_Pirate_Gunner x 2
	Wave 3 - entity:Skeleton_Pirate_Gunner x 4 + entity:Skeleton_Pirate_Striker x 3
	Wave 4 - entity:Skeleton_Pirate_Captain x 1 + entity:Skeleton_Pirate_Gunner x 3 + entity:Skeleton_Pirate_Striker x 4
}

class Costline <<Cost : 6 / Reward : 3>> {
	Ticks : 25
	ID: entity:Crab / Weight : 4
	ID: entity:Duck / Weight : 3
	ID: entity:Cactee / Weight : 1
	ID: Block_Sand / Weight : 26
	ID: Rock_Sandstone / Weight : 24
	ID: Rubble_Sandstone / Weight : 22
	ID: Plant_Coral_Bush_Yellow / Weight : 12
	ID: Plant_Coral_Model_Yellow / Weight : 10
	ID: Rock_Gem_Sapphire / Weight : 3
}

class SeaCavern <<Cost : 9 / Reward : 4>> {
	Ticks : 28
	ID: entity:Crab / Weight : 3
	ID: entity:Cave_Spider / Weight : 2
	ID: entity:Scarak_Louse / Weight : 1
	ID: Rock_Aqua_Brick / Weight : 22
	ID: Rock_Aqua_Brick_Smooth / Weight : 20
	ID: Rock_Aqua_Brick_Ornate / Weight : 10
	ID: Rock_Gem_Sapphire / Weight : 8
	ID: Rock_Gem_Diamond / Weight : 3
}

class SeaInfestedNest <<Cost : 13 / Reward : 6>> {
	Ticks : 28
	ID: entity:Scarak_Louse / Weight : 3
	ID: entity:Scarak_Fighter / Weight : 2
	ID: entity:Scarak_Seeker / Weight : 1
	ID: Soil_Hive / Weight : 24
	ID: Soil_Hive_Brick / Weight : 22
	ID: Soil_Hive_Brick_Smooth / Weight : 16
	ID: Ingredient_Hide_Scaled / Weight : 10
	ID: Ingredient_Leather_Scaled / Weight : 6
	ID: Rock_Gem_Sapphire / Weight : 6
	ID: Rock_Gem_Diamond / Weight : 2
}

enum SeaMonster <<Dungeon / Cost : 15 / Reward : 40>> {
	Wave 1 - entity:Scarak_Louse x 5 + entity:Spider x 3
	Wave 2 - entity:Scarak_Fighter x 4 + entity:Cave_Spider x 3
	Wave 3 - entity:Scarak_Defender x 3 + entity:Scarak_Seeker x 3 + entity:Cave_Spider x 4
	Wave 4 - entity:Scarak_Broodmother x 1 + entity:Scarak_Fighter x 6 + entity:Scarak_Seeker x 4
}

class Forest <<Cost : 3 / Reward : 2>> {
	Ticks : 25
	ID: entity:Boar / Weight : 3
	ID: entity:Boar_Piglet / Weight : 4
	ID: entity:Fox / Weight : 2
	ID: entity:Pigeon / Weight : 4
	ID: entity:Deer / Weight : 2
	ID: entity:Wolf / Weight : 1
	ID: Ingredient_Stick / Weight : 26
	ID: Wood_Oak_Trunk / Weight : 22
	ID: Wood_Beech_Trunk / Weight : 18
	ID: Wood_Ash_Trunk / Weight : 12
	ID: Plant_Sapling_Oak / Weight : 8
	ID: Plant_Sapling_Beech / Weight : 6
	ID: Plant_Sapling_Ash / Weight : 5
	ID: Plant_Fruit_Apple / Weight : 5
}

class AridForest <<Cost : 5 / Reward : 2>> {
	Ticks : 25
	ID: entity:Fox / Weight : 2
	ID: entity:Armadillo / Weight : 3
	ID: entity:Cactee / Weight : 1
	ID: Wood_Ash_Trunk / Weight : 24
	ID: Wood_Bottletree_Trunk / Weight : 14
	ID: Wood_Bottletree_Roots / Weight : 10
	ID: Plant_Leaves_Bottle / Weight : 12
	ID: Plant_Seeds_Bottletree / Weight : 8
	ID: Rock_Sandstone / Weight : 22
	ID: Rubble_Sandstone / Weight : 20
}

class Swamp <<Cost : 5 / Reward : 2>> {
	Ticks : 25
	ID: entity:Frog / Weight : 4
	ID: entity:Crocodile / Weight : 2
	ID: entity:Fen_Stalker / Weight : 1
	ID: Soil_Dirt / Weight : 22
	ID: Soil_Clay_Blue / Weight : 20
	ID: Plant_Moss_Block_Green / Weight : 18
	ID: Plant_Moss_Rug_Green / Weight : 18
	ID: Plant_Crop_Mushroom_Common_Brown / Weight : 12
	ID: Plant_Crop_Mushroom_Shelve_Brown / Weight : 8
	ID: Plant_Crop_Mushroom_Block_Yellow / Weight : 4
}

class EnchantedForest <<Cost : 8 / Reward : 4>> {
	Ticks : 25
	ID: entity:Deer / Weight : 3
	ID: entity:Bluebird / Weight : 4
	ID: entity:Earth_Elemental / Weight : 1
	ID: Wood_Amber_Trunk / Weight : 18
	ID: Wood_Amber_Roots / Weight : 12
	ID: Plant_Leaves_Amber / Weight : 14
	ID: Plant_Leaves_Goldentree / Weight : 12
	ID: Plant_Flower_Common_Yellow / Weight : 14
	ID: Plant_Flower_Orchid_Yellow / Weight : 8
	ID: Rock_Gem_Emerald / Weight : 8
	ID: Rock_Gem_Topaz / Weight : 3
}

class FairyPond <<Cost : 10 / Reward : 5>> {
	Ticks : 25
	ID: entity:Frog / Weight : 3
	ID: entity:Duck / Weight : 3
	ID: entity:Bluebird / Weight : 4
	ID: entity:Earth_Elemental / Weight : 1
	ID: Plant_Flower_Common_Pink2 / Weight : 14
	ID: Plant_Flower_Common_Yellow / Weight : 14
	ID: Plant_Flower_Orchid_Yellow / Weight : 8
	ID: Plant_Petals_Yellow / Weight : 12
	ID: Plant_Moss_Yellow / Weight : 16
	ID: Plant_Moss_Block_Yellow / Weight : 14
	ID: Rock_Gem_Topaz / Weight : 6
}

class DeepForest <<Cost : 7 / Reward : 3>> {
	Ticks : 25
	ID: entity:Boar / Weight : 3
	ID: entity:Fox / Weight : 2
	ID: entity:Wolf / Weight : 2
	ID: entity:Crawler / Weight : 1
	ID: Wood_Beech_Trunk / Weight : 22
	ID: Wood_Ash_Trunk / Weight : 18
	ID: Wood_Maple_Trunk / Weight : 14
	ID: Plant_Sapling_Beech / Weight : 8
	ID: Plant_Sapling_Ash / Weight : 7
	ID: Plant_Crop_Mushroom_Block_Yellow / Weight : 8
	ID: Plant_Crop_Mushroom_Block_Yellow_Trunk / Weight : 5
	ID: Rock_Gem_Emerald / Weight : 3
}

class DarkForest <<Cost : 10 / Reward : 5>> {
	Ticks : 25
	ID: entity:Wolf / Weight : 2
	ID: entity:Crawler / Weight : 2
	ID: entity:Zombie / Weight : 2
	ID: entity:Aberrant_Zombie / Weight : 1
	ID: Plant_Leaves_Bramble / Weight : 20
	ID: Plant_Crop_Mushroom_Block_Yellow / Weight : 14
	ID: Plant_Crop_Mushroom_Block_Yellow_Mycelium / Weight : 10
	ID: Plant_Crop_Mushroom_Shelve_Yellow / Weight : 8
	ID: Ingredient_Bone_Fragment / Weight : 10
	ID: Rock_Gem_Ruby / Weight : 3
}

class BurnedForest <<Cost : 12 / Reward : 5>> {
	Ticks : 25
	ID: entity:Zombie_Burnt / Weight : 2
	ID: entity:Emberwulf / Weight : 2
	ID: entity:Burnt_Skeleton_Archer / Weight : 1
	ID: Wood_Ash_Trunk / Weight : 20
	ID: Ingredient_Fire_Essence / Weight : 8
	ID: Rock_Volcanic / Weight : 22
	ID: Rubble_Volcanic / Weight : 20
	ID: Ingredient_Powder_Boom / Weight : 6
	ID: Ore_Thorium / Weight : 3
}

class CursedForest <<Cost : 13 / Reward : 6>> {
	Ticks : 25
	ID: entity:Zombie / Weight : 3
	ID: entity:Aberrant_Zombie / Weight : 2
	ID: entity:Skeleton_Scout / Weight : 2
	ID: entity:Skeleton_Archer / Weight : 1
	ID: Ingredient_Bone_Fragment / Weight : 20
	ID: Deco_Bone_Full / Weight : 10
	ID: Deco_Bone_Spike / Weight : 10
	ID: Deco_Bone_Spine / Weight : 6
	ID: Plant_Leaves_Bramble / Weight : 16
	ID: Rock_Runic_Brick / Weight : 10
	ID: Rock_Gem_Zephyr / Weight : 3
}

class Graveyard <<Cost : 15 / Reward : 7>> {
	Ticks : 25
	ID: entity:Zombie / Weight : 3
	ID: entity:Skeleton_Scout / Weight : 3
	ID: entity:Skeleton_Archer / Weight : 2
	ID: entity:Skeleton_Soldier / Weight : 2
	ID: entity:Skeleton_Mage / Weight : 1
	ID: Ingredient_Bone_Fragment / Weight : 24
	ID: Deco_Bone_Full / Weight : 12
	ID: Deco_Bone_Spike / Weight : 10
	ID: Furniture_Village_Tombstone / Weight : 8
	ID: Furniture_Ancient_Coffin / Weight : 4
	ID: Weapon_Club_Zombie_Arm / Weight : 2
	ID: Weapon_Club_Zombie_Leg / Weight : 2
}

enum UndeadTemple <<Dungeon / Cost : 17 / Reward : 45>> {
	Wave 1 - entity:Skeleton_Scout x 3 + entity:Zombie x 2
	Wave 2 - entity:Skeleton_Soldier x 3 + entity:Skeleton_Archer x 2
	Wave 3 - entity:Skeleton_Knight x 2 + entity:Skeleton_Ranger x 3
	Wave 4 - entity:Skeleton_Mage x 2 + entity:Skeleton_Knight x 3 + entity:Zombie x 4
}

class VoidPortal <<Cost : 20 / Reward : 8>> {
	Ticks : 25
	ID: entity:Void_Larva / Weight : 3
	ID: entity:Void_Crawler / Weight : 2
	ID: entity:Void_Eye / Weight : 1
	ID: Portal_Device / Weight : 5
	ID: Instance_Gateway / Weight : 4
	ID: Rock_Runic_Brick / Weight : 20
	ID: Rock_Runic_Brick_Ornate / Weight : 12
	ID: Rock_Gem_Zephyr / Weight : 8
	ID: Ore_Onyxium / Weight : 3
}

enum VoidTemple <<Dungeon / Cost : 24 / Reward : 75>> {
	Wave 1 - entity:Void_Larva x 6 + entity:Void_Crawler x 2
	Wave 2 - entity:Void_Crawler x 5 + entity:Void_Eye x 2
	Wave 3 - entity:Void_Spawn x 4 + entity:Void_Spectre x 2
	Wave 4 - entity:Void_Spawn x 6 + entity:Void_Spectre x 4 + entity:Void_Eye x 3
}

class OutlanderForest <<Cost : 15 / Reward : 7>> {
	Ticks : 25
	ID: entity:Outlander_Initiate / Weight : 3
	ID: entity:Outlander_Hunter / Weight : 2
	ID: entity:Outlander_Marauder / Weight : 1
	ID: Wood_Amber_Trunk / Weight : 18
	ID: Wood_Amber_Roots / Weight : 12
	ID: Plant_Leaves_Amber / Weight : 14
	ID: Plant_Leaves_Bramble / Weight : 12
	ID: Ingredient_Hide_Prismic / Weight : 4
	ID: Rock_Gem_Zephyr / Weight : 3
}

class OutlanderPlain <<Cost : 16 / Reward : 7>> {
	Ticks : 25
	ID: entity:Outlander_Initiate / Weight : 3
	ID: entity:Outlander_Hunter / Weight : 3
	ID: entity:Outlander_Berserker / Weight : 2
	ID: entity:Outlander_Marauder / Weight : 2
	ID: entity:Outlander_Priest / Weight : 1
	ID: entity:Outlander_Brute / Weight : 1
	ID: Plant_Crop_Wheat_Item / Weight : 20
	ID: Plant_Crop_Corn_Item / Weight : 18
	ID: Plant_Crop_Carrot_Item / Weight : 16
	ID: Ingredient_Hide_Prismic / Weight : 8
	ID: Ingredient_Leather_Prismic / Weight : 6
	ID: Ore_Adamantite / Weight : 3
}

enum OutlanderGank <<Dungeon / Cost : 17 / Reward : 42>> {
	Wave 1 - entity:Outlander_Initiate x 4 + entity:Outlander_Hunter x 1
	Wave 2 - entity:Outlander_Initiate x 3 + entity:Outlander_Hunter x 2 + entity:Outlander_Marauder x 1
	Wave 3 - entity:Outlander_Berserker x 2 + entity:Outlander_Marauder x 3
	Wave 4 - entity:Outlander_Berserker x 3 + entity:Outlander_Hunter x 3 + entity:Outlander_Marauder x 2
}

enum OutlanderCity <<Dungeon / Cost : 20 / Reward : 60>> {
	Wave 1 - entity:Outlander_Initiate x 5 + entity:Outlander_Hunter x 3
	Wave 2 - entity:Outlander_Marauder x 4 + entity:Outlander_Berserker x 3
	Wave 3 - entity:Outlander_Marauder x 5 + entity:Outlander_Hunter x 4 + entity:Outlander_Priest x 1
	Wave 4 - entity:Outlander_Berserker x 4 + entity:Outlander_Brute x 1 + entity:Outlander_Priest x 1
	Wave 5 - entity:Outlander_Brute x 2 + entity:Outlander_Priest x 2 + entity:Outlander_Marauder x 4
}

class Toundra <<Cost : 17 / Reward : 8>> {
	Ticks : 25
	ID: entity:Wolf / Weight : 2
	ID: entity:Frost_Zombie / Weight : 2
	ID: entity:Frost_Skeleton_Scout / Weight : 1
	ID: Rock_Ice / Weight : 24
	ID: Rubble_Ice / Weight : 24
	ID: Rubble_Ice_Medium / Weight : 14
	ID: Wood_Ice_Trunk / Weight : 14
	ID: Plant_Seeds_Ice / Weight : 8
	ID: Ingredient_Ice_Essence / Weight : 3
}

class FrozenForest <<Cost : 18 / Reward : 8>> {
	Ticks : 25
	ID: entity:Wolf / Weight : 2
	ID: entity:Frost_Zombie / Weight : 2
	ID: entity:Frost_Skeleton_Ranger / Weight : 1
	ID: Wood_Birch_Trunk / Weight : 18
	ID: Plant_Sapling_Birch / Weight : 8
	ID: Plant_Leaves_Birch / Weight : 14
	ID: Wood_Ice_Trunk / Weight : 16
	ID: Rock_Ice / Weight : 20
	ID: Rubble_Ice / Weight : 18
	ID: Ingredient_Ice_Essence / Weight : 3
}

class IceLand <<Cost : 18 / Reward : 8>> {
	Ticks : 25
	ID: entity:Frost_Zombie / Weight : 2
	ID: entity:Frost_Skeleton_Scout / Weight : 2
	ID: entity:Frost_Golem / Weight : 1
	ID: Rock_Ice / Weight : 26
	ID: Rubble_Ice / Weight : 24
	ID: Rubble_Ice_Medium / Weight : 16
	ID: Rock_Ice_Icicles / Weight : 10
	ID: Wood_Ice_Trunk / Weight : 10
	ID: Ingredient_Ice_Essence / Weight : 5
}

class IcyCavern <<Cost : 20 / Reward : 9>> {
	Ticks : 28
	ID: entity:Frost_Zombie / Weight : 2
	ID: entity:Frost_Skeleton_Fighter / Weight : 2
	ID: entity:Frost_Skeleton_Mage / Weight : 1
	ID: Rock_Ice / Weight : 22
	ID: Rubble_Ice / Weight : 22
	ID: Rock_Ice_Icicles / Weight : 12
	ID: Ore_Silver / Weight : 12
	ID: Rock_Gem_Sapphire / Weight : 6
	ID: Ingredient_Ice_Essence / Weight : 4
}

class YetiCavern <<Cost : 22 / Reward : 10>> {
	Ticks : 28
	ID: entity:Frost_Golem / Weight : 2
	ID: entity:Frost_Skeleton_Knight / Weight : 2
	ID: entity:Ice_Dragon / Weight : 1
	ID: Rock_Ice / Weight : 22
	ID: Rubble_Ice_Medium / Weight : 18
	ID: Rock_Ice_Icicles / Weight : 12
	ID: Ingredient_Ice_Essence / Weight : 8
	ID: Rock_Gem_Diamond / Weight : 3
	ID: Weapon_Staff_Crystal_Ice / Weight : 1
}

enum IceTemple <<Dungeon / Cost : 24 / Reward : 75>> {
	Wave 1 - entity:Frost_Zombie x 4 + entity:Frost_Skeleton_Scout x 2
	Wave 2 - entity:Frost_Skeleton_Fighter x 4 + entity:Frost_Skeleton_Ranger x 2
	Wave 3 - entity:Frost_Golem x 2 + entity:Frost_Skeleton_Mage x 3
	Wave 4 - entity:Ice_Dragon x 1 + entity:Frost_Skeleton_Knight x 4 + entity:Frost_Zombie x 6
}

class IcyForest <<Cost : 20 / Reward : 9>> {
	Ticks : 25
	ID: entity:Wolf / Weight : 2
	ID: entity:Frost_Zombie / Weight : 2
	ID: entity:Frost_Skeleton_Ranger / Weight : 2
	ID: entity:Frost_Golem / Weight : 1
	ID: Wood_Ice_Trunk / Weight : 18
	ID: Plant_Seeds_Ice / Weight : 8
	ID: Plant_Leaves_Birch / Weight : 12
	ID: Wood_Birch_Trunk / Weight : 16
	ID: Rock_Ice / Weight : 20
	ID: Ingredient_Ice_Essence / Weight : 6
}

class FireLand <<Cost : 16 / Reward : 7>> {
	Ticks : 25
	ID: entity:Zombie_Burnt / Weight : 2
	ID: entity:Emberwulf / Weight : 2
	ID: entity:Burnt_Skeleton_Soldier / Weight : 1
	ID: Rock_Volcanic / Weight : 26
	ID: Rubble_Volcanic / Weight : 24
	ID: Rubble_Volcanic_Medium / Weight : 16
	ID: Ingredient_Fire_Essence / Weight : 8
	ID: Ore_Thorium / Weight : 8
	ID: Ore_Cobalt / Weight : 3
}

enum Volcano <<Dungeon / Cost : 19 / Reward : 55>> {
	Wave 1 - entity:Zombie_Burnt x 5 + entity:Emberwulf x 2
	Wave 2 - entity:Burnt_Skeleton_Soldier x 4 + entity:Burnt_Skeleton_Archer x 3
	Wave 3 - entity:Burnt_Skeleton_Knight x 3 + entity:Burnt_Skeleton_Wizard x 2
	Wave 4 - entity:Ember_Golem x 2 + entity:Burnt_Skeleton_Praetorian x 3 + entity:Emberwulf x 4
}

class FieryGraveward <<Cost : 17 / Reward : 8>> {
	Ticks : 25
	ID: entity:Zombie_Burnt / Weight : 2
	ID: entity:Burnt_Skeleton_Soldier / Weight : 2
	ID: entity:Burnt_Skeleton_Archer / Weight : 2
	ID: entity:Burnt_Skeleton_Knight / Weight : 1
	ID: Ingredient_Bone_Fragment / Weight : 18
	ID: Deco_Bone_Full / Weight : 10
	ID: Deco_Bone_Spike / Weight : 10
	ID: Rock_Volcanic / Weight : 22
	ID: Ingredient_Fire_Essence / Weight : 8
	ID: Rock_Gem_Ruby / Weight : 3
}

class HellGate <<Cost : 20 / Reward : 9>> {
	Ticks : 25
	ID: entity:Incandescent_Skeleton_Fighter / Weight : 2
	ID: entity:Incandescent_Skeleton_Mage / Weight : 1
	ID: entity:Ember_Golem / Weight : 1
	ID: Portal_Device / Weight : 5
	ID: Rock_Volcanic_Cracked_Incandescent / Weight : 18
	ID: Rock_Volcanic_Cracked_Lava_Incandescent / Weight : 16
	ID: Ingredient_Fire_Essence / Weight : 8
	ID: Ore_Mithril / Weight : 3
	ID: Ore_Onyxium / Weight : 2
}

class HellPlain <<Cost : 22 / Reward : 10>> {
	Ticks : 25
	ID: entity:Incandescent_Skeleton_Fighter / Weight : 2
	ID: entity:Incandescent_Skeleton_Footman / Weight : 2
	ID: entity:Emberwulf / Weight : 2
	ID: entity:Firesteel_Golem / Weight : 1
	ID: Rock_Volcanic / Weight : 22
	ID: Rubble_Volcanic / Weight : 22
	ID: Ingredient_Fire_Essence / Weight : 8
	ID: Ingredient_Bolt_Cindercloth / Weight : 6
	ID: Ore_Mithril / Weight : 8
	ID: Ore_Onyxium / Weight : 3
}

class HellSwamp <<Cost : 22 / Reward : 10>> {
	Ticks : 25
	ID: entity:Fen_Stalker / Weight : 2
	ID: entity:Zombie_Burnt / Weight : 2
	ID: entity:Incandescent_Skeleton_Mage / Weight : 1
	ID: entity:Ember_Golem / Weight : 1
	ID: Soil_Clay_Black / Weight : 18
	ID: Plant_Moss_Yellow / Weight : 16
	ID: Plant_Moss_Block_Yellow / Weight : 14
	ID: Plant_Crop_Mushroom_Block_Yellow / Weight : 10
	ID: Ingredient_Fire_Essence / Weight : 8
	ID: Rock_Gem_Ruby / Weight : 6
	ID: Ore_Onyxium / Weight : 3
}

class FireGemCave <<Cost : 24 / Reward : 11>> {
	Ticks : 28
	ID: entity:Incandescent_Skeleton_Fighter / Weight : 2
	ID: entity:Incandescent_Skeleton_Mage / Weight : 1
	ID: entity:Firesteel_Golem / Weight : 1
	ID: entity:Thunder_Golem / Weight : 1
	ID: Rock_Volcanic / Weight : 20
	ID: Rock_Volcanic_Cracked_Incandescent / Weight : 14
	ID: Rock_Gem_Ruby / Weight : 10
	ID: Rock_Gem_Diamond / Weight : 5
	ID: Ore_Onyxium / Weight : 8
	ID: Ore_Prisma / Weight : 3
}

class DesertTempleEntrace <<Cost : 9 / Reward : 4>> {
	Ticks : 25
	ID: entity:Sandswept_Zombie / Weight : 2
	ID: entity:Skeleton_Scout / Weight : 2
	ID: entity:Skeleton_Archer / Weight : 1
	ID: Rock_Sandstone / Weight : 24
	ID: Rubble_Sandstone / Weight : 22
	ID: Furniture_Ancient_Pot / Weight : 10
	ID: Furniture_Ancient_Crate / Weight : 8
	ID: Deco_Pot_Clay_Broken / Weight : 10
	ID: Ore_Gold / Weight : 3
}

class DeeperDesertTemple <<Cost : 11 / Reward : 5>> {
	Ticks : 25
	ID: entity:Sandswept_Zombie / Weight : 2
	ID: entity:Skeleton_Soldier / Weight : 2
	ID: entity:Skeleton_Archer / Weight : 2
	ID: entity:Skeleton_Mage / Weight : 1
	ID: Rock_Sandstone / Weight : 22
	ID: Rock_Sandstone_Brick / Weight : 18
	ID: Furniture_Ancient_Pot / Weight : 8
	ID: Furniture_Ancient_Statue / Weight : 6
	ID: Furniture_Ancient_Candle / Weight : 8
	ID: Rock_Gem_Topaz / Weight : 5
	ID: Ore_Gold / Weight : 8
}

enum DesertTemple <<Dungeon / Cost : 13 / Reward : 35>> {
	Wave 1 - entity:Sandswept_Zombie x 4 + entity:Skeleton_Scout x 2
	Wave 2 - entity:Sandswept_Zombie x 5 + entity:Skeleton_Archer x 3
	Wave 3 - entity:Skeleton_Knight x 3 + entity:Skeleton_Mage x 2 + entity:Sandswept_Zombie x 4
	Wave 4 - entity:Skeleton_Sand_Archmage x 1 + entity:Skeleton_Soldier x 6 + entity:Skeleton_Archer x 4
}

class PharaonRoom <<Cost : 15 / Reward : 7>> {
	Ticks : 25
	ID: entity:Sandswept_Zombie / Weight : 2
	ID: entity:Skeleton_Knight / Weight : 2
	ID: entity:Skeleton_Mage / Weight : 1
	ID: entity:Skeleton_Sand_Archmage / Weight : 1
	ID: Deco_Treasure / Weight : 6
	ID: Furniture_Ancient_Coffin / Weight : 8
	ID: Furniture_Ancient_Statue / Weight : 8
	ID: Furniture_Ancient_Chest_Large_Treasure / Weight : 4
	ID: Ore_Gold / Weight : 12
	ID: Rock_Gem_Diamond / Weight : 3
}

class InnerDesert <<Cost : 8 / Reward : 4>> {
	Ticks : 25
	ID: entity:Cactee / Weight : 2
	ID: entity:Camel / Weight : 3
	ID: entity:Sandswept_Zombie / Weight : 1
	ID: entity:Scarak_Louse / Weight : 1
	ID: Block_Sand / Weight : 30
	ID: Rock_Sandstone / Weight : 24
	ID: Rubble_Sandstone / Weight : 20
	ID: Plant_Cactus_1 / Weight : 14
	ID: Plant_Cactus_Ball_1 / Weight : 10
	ID: Plant_Cactus_Flat_1 / Weight : 10
	ID: Ore_Gold / Weight : 3
}

class MuddyDesert <<Cost : 9 / Reward : 4>> {
	Ticks : 25
	ID: entity:Cactee / Weight : 2
	ID: entity:Crocodile / Weight : 2
	ID: entity:Scarak_Louse / Weight : 1
	ID: Block_Sand / Weight : 22
	ID: Soil_Dirt / Weight : 22
	ID: Soil_Clay_Black / Weight : 18
	ID: Soil_Gravel_Sand_Half / Weight : 16
	ID: Plant_Cactus_1 / Weight : 12
	ID: Plant_Crop_Tomato_Item / Weight : 8
}

enum InsectInvasion <<Dungeon / Cost : 10 / Reward : 26>> {
	Wave 1 - entity:Scarak_Louse x 4 + entity:Spider x 3
	Wave 2 - entity:Scarak_Fighter x 3 + entity:Scarak_Louse x 4
	Wave 3 - entity:Scarak_Seeker x 2 + entity:Cave_Spider x 4 + entity:Scarak_Fighter x 3
}

class InfestedDesert <<Cost : 11 / Reward : 5>> {
	Ticks : 25
	ID: entity:Scarak_Louse / Weight : 3
	ID: entity:Scarak_Fighter / Weight : 2
	ID: entity:Scarak_Seeker / Weight : 1
	ID: Soil_Hive / Weight : 24
	ID: Soil_Hive_Brick / Weight : 20
	ID: Soil_Hive_Brick_Smooth / Weight : 16
	ID: Soil_Hive_Brick_Stairs / Weight : 10
	ID: Plant_Cactus_Ball_1 / Weight : 8
	ID: Ingredient_Hide_Scaled / Weight : 6
}

enum InsectNest <<Dungeon / Cost : 13 / Reward : 36>> {
	Wave 1 - entity:Scarak_Louse x 6 + entity:Spider x 4
	Wave 2 - entity:Scarak_Fighter x 5 + entity:Cave_Spider x 4
	Wave 3 - entity:Scarak_Defender x 2 + entity:Scarak_Fighter x 5 + entity:Scarak_Seeker x 2
	Wave 3 - entity:Sand_Empress x 1 + entity:Scarak_Fighter x 2 + entity:Scarak_Fighter x 1
}

class InsideInsectNest <<Cost : 14 / Reward : 6>> {
	Ticks : 25
	ID: entity:Scarak_Louse / Weight : 3
	ID: entity:Scarak_Fighter / Weight : 2
	ID: entity:Scarak_Defender / Weight : 1
	ID: entity:Scarak_Seeker / Weight : 1
	ID: Soil_Hive / Weight : 22
	ID: Soil_Hive_Brick / Weight : 20
	ID: Soil_Hive_Brick_Smooth / Weight : 16
	ID: Soil_Hive_Brick_Beam / Weight : 10
	ID: Soil_Hive_Brick_Stairs / Weight : 10
	ID: Rock_Gem_Ruby / Weight : 5
}

enum InsectCore <<Dungeon / Cost : 17 / Reward : 50>> {
	Wave 1 - entity:Scarak_Louse x 8 + entity:Scarak_Fighter x 4
	Wave 2 - entity:Scarak_Defender x 3 + entity:Scarak_Seeker x 3
	Wave 3 - entity:Scarak_Fighter x 6 + entity:Scarak_Defender x 4 + entity:Cave_Spider x 4
	Wave 4 - entity:Scarak_Broodmother x 1 + entity:Scarak_Defender x 4 + entity:Scarak_Seeker x 4
}

class Quarry <<Cost : 3 / Reward : 2>> {
	Ticks : 50
	ID: entity:Bat / Weight : 2
	ID: entity:Goblin_Miner / Weight : 1
	ID: Rubble_Stone / Weight : 45
	ID: Rock_Stone / Weight : 45
	ID: Rock_Slate / Weight : 22
	ID: Rock_Shale / Weight : 20
	ID: Rock_Basalt / Weight : 14
	ID: Ore_Copper / Weight : 8
	ID: Ore_Iron / Weight : 2
}

class Hallow <<Cost : 3 / Reward : 2>> {
	Ticks : 30
	ID: entity:Rabbit / Weight : 4
	ID: entity:Sheep / Weight : 4
	ID: entity:Chicken / Weight : 4
	ID: entity:Deer / Weight : 1
	ID: Plant_Crop_Wheat_Item / Weight : 30
	ID: Plant_Crop_Corn_Item / Weight : 20
	ID: Plant_Crop_Carrot_Item / Weight : 20
	ID: Food_Bread / Weight : 8
	ID: Plant_Fruit_Apple / Weight : 8
}

class CowHallow <<Cost : 5 / Reward : 2>> {
	Ticks : 35
	ID: entity:Cow / Weight : 5
	ID: entity:Cow_Calf / Weight : 4
	ID: entity:Wolf / Weight : 1
	ID: Plant_Crop_Wheat_Item / Weight : 30
	ID: Plant_Crop_Corn_Item / Weight : 24
	ID: Ingredient_Bolt_Wool / Weight : 8
	ID: Food_Bread / Weight : 8
	ID: Plant_Fruit_Apple / Weight : 8
}

class HorseHallow <<Cost : 5 / Reward : 2>> {
	Ticks : 35
	ID: entity:Horse / Weight : 5
	ID: entity:Wolf / Weight : 1
	ID: Plant_Crop_Carrot_Item / Weight : 30
	ID: Plant_Crop_Wheat_Item / Weight : 24
	ID: Ingredient_Bolt_Wool / Weight : 8
	ID: Food_Bread / Weight : 8
	ID: Plant_Fruit_Apple / Weight : 8
}

class MysteriousCavern <<Cost : 6 / Reward : 3>> {
	Ticks : 30
	ID: entity:Bat / Weight : 3
	ID: entity:Cave_Spider / Weight : 2
	ID: entity:Earth_Elemental / Weight : 1
	ID: Rubble_Stone / Weight : 24
	ID: Rock_Stone / Weight : 24
	ID: Rock_Slate / Weight : 18
	ID: Rock_Shale / Weight : 18
	ID: Rock_Gem_Sapphire / Weight : 3
	ID: Ore_Iron / Weight : 8
}

class MysticCave <<Cost : 9 / Reward : 4>> {
	Ticks : 30
	ID: entity:Earth_Elemental / Weight : 2
	ID: entity:Earthen_Golem / Weight : 1
	ID: Rock_Runic_Brick / Weight : 22
	ID: Rock_Runic_Brick_Ornate / Weight : 12
	ID: Rock_Gem_Sapphire / Weight : 8
	ID: Rock_Gem_Emerald / Weight : 6
	ID: Ingredient_Crystal_Yellow / Weight : 3
}

class LuxirousCave <<Cost : 13 / Reward : 6>> {
	Ticks : 30
	ID: entity:Earth_Elemental / Weight : 2
	ID: entity:Earthen_Golem / Weight : 2
	ID: entity:Goblin_Thief / Weight : 1
	ID: Rock_Gem_Emerald / Weight : 10
	ID: Rock_Gem_Topaz / Weight : 8
	ID: Rock_Gem_Diamond / Weight : 3
	ID: Ore_Gold / Weight : 12
	ID: Ore_Adamantite / Weight : 3
	ID: Deco_Treasure / Weight : 4
}

class JurassicCave <<Cost : 17 / Reward : 8>> {
	Ticks : 30
	ID: entity:Archaeopteryx / Weight : 3
	ID: entity:Crocodile / Weight : 2
	ID: entity:Cave_Raptor / Weight : 2
	ID: entity:Cave_Rex / Weight : 1
	ID: Ingredient_Bone_Fragment / Weight : 20
	ID: Deco_Bone_Full / Weight : 10
	ID: Deco_Bone_Spike_Large / Weight : 8
	ID: Ingredient_Hide_Scaled / Weight : 10
	ID: Ingredient_Leather_Scaled / Weight : 6
	ID: Rock_Gem_Diamond / Weight : 4
	ID: Ore_Adamantite / Weight : 8
}

enum DinoCrisis <<Dungeon / Cost : 21 / Reward : 65>> {
	Wave 1 - entity:Archaeopteryx x 5 + entity:Crocodile x 2
	Wave 2 - entity:Cave_Raptor x 4 + entity:Archaeopteryx x 3
	Wave 3 - entity:Cave_Raptor x 6 + entity:Crawler x 2
	Wave 4 - entity:Cave_Raptor x 5 + entity:Cave_Rex x 1
	Wave 5 - entity:Cave_Raptor x 4 + entity:Cave_Rex x 2
	Wave 6 - entity:Cave_Rex x 3 + entity:Earth_Elemental x 1
}

class DryTrorkCamp <<Cost : 10 / Reward : 5>> {
	Ticks : 25
	ID: entity:Trork_Sentry / Weight : 3
	ID: entity:Trork_Hunter / Weight : 2
	ID: entity:Hunting_Wolf / Weight : 2
	ID: entity:Trork_Brawler / Weight : 1
	ID: Wood_Ash_Trunk / Weight : 18
	ID: Rock_Sandstone / Weight : 22
	ID: Rubble_Sandstone / Weight : 20
	ID: Ingredient_Bone_Fragment / Weight : 8
	ID: Ingredient_Hide_Scaled / Weight : 6
	ID: Ore_Gold / Weight : 3
}

class TrorkHuntingGround <<Cost : 10 / Reward : 5>> {
	Ticks : 25
	ID: entity:Hunting_Wolf / Weight : 4
	ID: entity:Trork_Hunter / Weight : 3
	ID: entity:Trork_Sentry / Weight : 2
	ID: entity:Trork_Brawler / Weight : 1
	ID: Wood_Beech_Trunk / Weight : 20
	ID: Wood_Ash_Trunk / Weight : 18
	ID: Plant_Leaves_Bramble / Weight : 14
	ID: Ingredient_Bone_Fragment / Weight : 8
	ID: Ingredient_Hide_Scaled / Weight : 6
	ID: Rock_Gem_Emerald / Weight : 3
}

enum TrorkWarband <<Dungeon / Cost : 12 / Reward : 32>> {
	Wave 1 - entity:Hunting_Wolf x 3 + entity:Trork_Sentry x 2
	Wave 2 - entity:Trork_Hunter x 3 + entity:Trork_Brawler x 2
	Wave 3 - entity:Trork_Warrior x 3 + entity:Trork_Mauler x 1
	Wave 4 - entity:Trork_Guard x 2 + entity:Trork_Warrior x 3 + entity:Hunting_Wolf x 2
}

class TrorkStrongholdApproach <<Cost : 14 / Reward : 6>> {
	Ticks : 25
	ID: entity:Trork_Sentry / Weight : 3
	ID: entity:Trork_Warrior / Weight : 3
	ID: entity:Trork_Guard / Weight : 2
	ID: entity:Trork_Mauler / Weight : 1
	ID: Rock_Sandstone / Weight : 18
	ID: Rock_Runic_Brick / Weight : 14
	ID: Ingredient_Bone_Fragment / Weight : 10
	ID: Ingredient_Hide_Scaled / Weight : 8
	ID: Ingredient_Leather_Scaled / Weight : 5
	ID: Ore_Thorium / Weight : 4
}

class TrorkElderGrove <<Cost : 15 / Reward : 7>> {
	Ticks : 25
	ID: entity:Trork_Elder / Weight : 2
	ID: entity:Trork_Hunter / Weight : 2
	ID: entity:Trork_Guard / Weight : 2
	ID: entity:Hunting_Wolf / Weight : 2
	ID: Wood_Amber_Trunk / Weight : 14
	ID: Wood_Amber_Roots / Weight : 10
	ID: Plant_Leaves_Amber / Weight : 12
	ID: Plant_Leaves_Bramble / Weight : 12
	ID: Rock_Gem_Emerald / Weight : 5
	ID: Rock_Gem_Zephyr / Weight : 2
}

enum TrorkChieftainCamp <<Dungeon / Cost : 18 / Reward : 55>> {
	Wave 1 - entity:Trork_Sentry x 4 + entity:Hunting_Wolf x 3
	Wave 2 - entity:Trork_Brawler x 3 + entity:Trork_Hunter x 3
	Wave 3 - entity:Trork_Warrior x 4 + entity:Trork_Mauler x 2
	Wave 4 - entity:Trork_Guard x 4 + entity:Trork_Elder x 2
	Wave 5 - entity:Trork_Chieftain x 1 + entity:Trork_Guard x 3 + entity:Trork_Warrior x 4
}

class FrozenGraveyard <<Cost : 21 / Reward : 9>> {
	Ticks : 25
	ID: entity:Frost_Skeleton_Scout / Weight : 4
	ID: entity:Frost_Skeleton_Ranger / Weight : 3
	ID: entity:Frost_Skeleton_Fighter / Weight : 3
	ID: entity:Frost_Skeleton_Archer / Weight : 2
	ID: entity:Frost_Skeleton_Soldier / Weight : 2
	ID: entity:Frost_Skeleton_Mage / Weight : 1
	ID: Ingredient_Bone_Fragment / Weight : 24
	ID: Deco_Bone_Full / Weight : 12
	ID: Deco_Bone_Spike / Weight : 10
	ID: Deco_Bone_Spine / Weight : 8
	ID: Rock_Ice / Weight : 18
	ID: Rubble_Ice / Weight : 16
	ID: Rock_Ice_Icicles / Weight : 8
	ID: Ingredient_Ice_Essence / Weight : 4
	ID: Rock_Gem_Sapphire / Weight : 3
}

class IcyNecropolis <<Cost : 23 / Reward : 10>> {
	Ticks : 25
	ID: entity:Frost_Skeleton_Ranger / Weight : 3
	ID: entity:Frost_Skeleton_Fighter / Weight : 3
	ID: entity:Frost_Skeleton_Archer / Weight : 3
	ID: entity:Frost_Skeleton_Mage / Weight : 2
	ID: entity:Frost_Skeleton_Soldier / Weight : 2
	ID: entity:Frost_Skeleton_Knight / Weight : 2
	ID: entity:Frost_Skeleton_Archmage / Weight : 1
	ID: Ingredient_Bone_Fragment / Weight : 20
	ID: Deco_Bone_Full / Weight : 12
	ID: Deco_Bone_Spike / Weight : 10
	ID: Deco_Bone_Spine / Weight : 10
	ID: Rock_Ice / Weight : 16
	ID: Rubble_Ice / Weight : 14
	ID: Rock_Ice_Icicles / Weight : 10
	ID: Ingredient_Ice_Essence / Weight : 6
	ID: Rock_Gem_Sapphire / Weight : 5
	ID: Rock_Gem_Diamond / Weight : 2
}

enum FrostboneCrypt <<Dungeon / Cost : 25 / Reward : 80>> {
	Wave 1 - entity:Frost_Skeleton_Scout x 4 + entity:Frost_Skeleton_Ranger x 2
	Wave 2 - entity:Frost_Skeleton_Fighter x 4 + entity:Frost_Skeleton_Archer x 3
	Wave 3 - entity:Frost_Skeleton_Soldier x 4 + entity:Frost_Skeleton_Mage x 3
	Wave 4 - entity:Frost_Skeleton_Knight x 3 + entity:Frost_Skeleton_Archmage x 2
	Wave 5 - entity:Frost_Skeleton_Knight x 4 + entity:Frost_Skeleton_Archmage x 3 + entity:Frost_Golem x 1
}

class BurntBattlefield <<Cost : 18 / Reward : 8>> {
	Ticks : 25
	ID: entity:Skeleton_Scout / Weight : 2
	ID: entity:Burnt_Skeleton_Soldier / Weight : 3
	ID: entity:Burnt_Skeleton_Archer / Weight : 2
	ID: entity:Burnt_Skeleton_Lancer / Weight : 2
	ID: entity:Burnt_Skeleton_Knight / Weight : 1
	ID: Ingredient_Bone_Fragment / Weight : 22
	ID: Deco_Bone_Full / Weight : 10
	ID: Deco_Bone_Spike / Weight : 10
	ID: Rock_Volcanic / Weight : 20
	ID: Rubble_Volcanic / Weight : 18
	ID: Ingredient_Fire_Essence / Weight : 6
	ID: Ore_Thorium / Weight : 4
	ID: Rock_Gem_Ruby / Weight : 3
}

class AshenCatacombs <<Cost : 20 / Reward : 9>> {
	Ticks : 25
	ID: entity:Burnt_Skeleton_Soldier / Weight : 3
	ID: entity:Burnt_Skeleton_Archer / Weight : 2
	ID: entity:Burnt_Skeleton_Lancer / Weight : 2
	ID: entity:Burnt_Skeleton_Gunner / Weight : 2
	ID: entity:Burnt_Skeleton_Wizard / Weight : 2
	ID: entity:Burnt_Skeleton_Knight / Weight : 1
	ID: Ingredient_Bone_Fragment / Weight : 20
	ID: Deco_Bone_Full / Weight : 12
	ID: Deco_Bone_Spike / Weight : 10
	ID: Deco_Bone_Spine / Weight : 8
	ID: Rock_Volcanic / Weight : 18
	ID: Rubble_Volcanic / Weight : 16
	ID: Rock_Volcanic_Cracked_Incandescent / Weight : 8
	ID: Ingredient_Fire_Essence / Weight : 8
	ID: Rock_Gem_Ruby / Weight : 5
	ID: Ore_Mithril / Weight : 3
}

enum BurntSkeletonCitadel <<Dungeon / Cost : 22 / Reward : 70>> {
	Wave 1 - entity:Burnt_Skeleton_Soldier x 4 + entity:Burnt_Skeleton_Archer x 3
	Wave 2 - entity:Burnt_Skeleton_Lancer x 4 + entity:Burnt_Skeleton_Gunner x 3
	Wave 3 - entity:Burnt_Skeleton_Knight x 4 + entity:Burnt_Skeleton_Wizard x 3
	Wave 4 - entity:Burnt_Skeleton_Praetorian x 2 + entity:Burnt_Skeleton_Knight x 4 + entity:Burnt_Skeleton_Gunner x 3
	Wave 5 - entity:Burnt_Skeleton_Praetorian x 3 + entity:Burnt_Skeleton_Wizard x 3 + entity:Burnt_Skeleton_Lancer x 4
}

class JungleEdge <<Cost : 9 / Reward : 4>> {
	Ticks : 25
	ID: entity:Parrot / Weight : 4
	ID: entity:Gecko / Weight : 4
	ID: entity:Frog / Weight : 3
	ID: entity:Marsh_Snake / Weight : 2
	ID: entity:Zombie / Weight : 1
	ID: Wood_Beech_Trunk / Weight : 18
	ID: Wood_Maple_Trunk / Weight : 16
	ID: Plant_Leaves_Bramble / Weight : 14
	ID: Plant_Moss_Block_Green / Weight : 14
	ID: Plant_Moss_Rug_Green / Weight : 12
	ID: Plant_Crop_Mushroom_Common_Brown / Weight : 8
	ID: Rock_Gem_Emerald / Weight : 3
}

class DryJunglePass <<Cost : 9 / Reward : 4>> {
	Ticks : 25
	ID: entity:Cactee / Weight : 2
	ID: entity:Gecko / Weight : 4
	ID: entity:Marsh_Snake / Weight : 2
	ID: entity:Sandswept_Zombie / Weight : 2
	ID: entity:Skeleton_Scout / Weight : 1
	ID: Block_Sand / Weight : 20
	ID: Rock_Sandstone / Weight : 20
	ID: Rubble_Sandstone / Weight : 18
	ID: Plant_Cactus_1 / Weight : 10
	ID: Plant_Moss_Block_Green / Weight : 10
	ID: Plant_Leaves_Bramble / Weight : 10
	ID: Rock_Gem_Topaz / Weight : 3
}

class OvergrownRuins <<Cost : 11 / Reward : 5>> {
	Ticks : 25
	ID: entity:Zombie / Weight : 2
	ID: entity:Skeleton_Scout / Weight : 2
	ID: entity:Skeleton_Archer / Weight : 1
	ID: entity:Crocodile / Weight : 1
	ID: entity:Rhino_Toad / Weight : 1
	ID: Wood_Maple_Trunk / Weight : 14
	ID: Plant_Leaves_Bramble / Weight : 16
	ID: Plant_Moss_Block_Green / Weight : 14
	ID: Plant_Moss_Rug_Green / Weight : 12
	ID: Rock_Runic_Brick / Weight : 14
	ID: Rock_Runic_Brick_Ornate / Weight : 8
	ID: Ingredient_Bone_Fragment / Weight : 8
	ID: Rock_Gem_Emerald / Weight : 4
}

class SunkenJungleRuins <<Cost : 11 / Reward : 5>> {
	Ticks : 25
	ID: entity:Sandswept_Zombie / Weight : 2
	ID: entity:Zombie / Weight : 2
	ID: entity:Skeleton_Soldier / Weight : 1
	ID: entity:Crocodile / Weight : 2
	ID: entity:Marsh_Snake / Weight : 2
	ID: Soil_Clay_Blue / Weight : 16
	ID: Soil_Dirt / Weight : 14
	ID: Plant_Moss_Block_Green / Weight : 16
	ID: Plant_Moss_Rug_Green / Weight : 14
	ID: Rock_Runic_Brick / Weight : 12
	ID: Rock_Sandstone_Brick / Weight : 10
	ID: Ingredient_Bone_Fragment / Weight : 8
	ID: Rock_Gem_Sapphire / Weight : 4
}

class LostNecropolis <<Cost : 15 / Reward : 7>> {
	Ticks : 25
	ID: entity:Skeleton_Soldier / Weight : 3
	ID: entity:Skeleton_Fighter / Weight : 3
	ID: entity:Skeleton_Archer / Weight : 2
	ID: entity:Skeleton_Ranger / Weight : 2
	ID: entity:Skeleton_Mage / Weight : 2
	ID: entity:Aberrant_Zombie / Weight : 2
	ID: entity:Large_Aberrant_Zombie / Weight : 1
	ID: Ingredient_Bone_Fragment / Weight : 20
	ID: Deco_Bone_Full / Weight : 12
	ID: Deco_Bone_Spike / Weight : 10
	ID: Rock_Runic_Brick / Weight : 16
	ID: Rock_Runic_Brick_Ornate / Weight : 10
	ID: Rock_Gem_Emerald / Weight : 5
	ID: Rock_Gem_Ruby / Weight : 3
}

class ShadowedJungleRoad <<Cost : 17 / Reward : 8>> {
	Ticks : 25
	ID: entity:Wraith / Weight : 2
	ID: entity:Skeleton_Horse / Weight : 2
	ID: entity:Armored_Skeleton_Horse / Weight : 1
	ID: entity:Skeleton_Knight / Weight : 2
	ID: entity:Skeleton_Archmage / Weight : 1
	ID: entity:Undead_Pig / Weight : 2
	ID: entity:Undead_Chicken / Weight : 2
	ID: Plant_Leaves_Bramble / Weight : 16
	ID: Rock_Runic_Brick / Weight : 16
	ID: Rock_Runic_Brick_Ornate / Weight : 10
	ID: Ingredient_Bone_Fragment / Weight : 16
	ID: Deco_Bone_Spine / Weight : 8
	ID: Rock_Gem_Zephyr / Weight : 3
}

class ArmoredDeadGrove <<Cost : 19 / Reward : 9>> {
	Ticks : 25
	ID: entity:Armored_Skeleton_Horse / Weight : 2
	ID: entity:Skeleton_Horse / Weight : 2
	ID: entity:Shadow_Knight / Weight : 1
	ID: entity:Wraith / Weight : 2
	ID: entity:Skeleton_Knight / Weight : 3
	ID: entity:Skeleton_Archmage / Weight : 2
	ID: entity:Ghoul / Weight : 2
	ID: Wood_Amber_Trunk / Weight : 12
	ID: Plant_Leaves_Bramble / Weight : 16
	ID: Rock_Runic_Brick / Weight : 16
	ID: Ingredient_Bone_Fragment / Weight : 14
	ID: Deco_Bone_Full / Weight : 8
	ID: Deco_Bone_Spine / Weight : 8
	ID: Rock_Gem_Zephyr / Weight : 4
}

enum JungleCrypt <<Dungeon / Cost : 13 / Reward : 36>> {
	Wave 1 - entity:Zombie x 4 + entity:Sandswept_Zombie x 3
	Wave 2 - entity:Skeleton_Scout x 4 + entity:Skeleton_Archer x 3
	Wave 3 - entity:Skeleton_Soldier x 4 + entity:Skeleton_Fighter x 3
	Wave 4 - entity:Skeleton_Knight x 2 + entity:Skeleton_Ranger x 4 + entity:Skeleton_Mage x 2
}

enum AncientUndeadSanctum <<Dungeon / Cost : 18 / Reward : 58>> {
	Wave 1 - entity:Zombie x 4 + entity:Aberrant_Zombie x 3 + entity:Small_Aberrant_Zombie x 4
	Wave 2 - entity:Skeleton_Soldier x 4 + entity:Skeleton_Archer x 4 + entity:Skeleton_Fighter x 3
	Wave 3 - entity:Skeleton_Knight x 4 + entity:Skeleton_Mage x 3 + entity:Large_Aberrant_Zombie x 2
	Wave 4 - entity:Skeleton_Archmage x 2 + entity:Skeleton_Ranger x 4 + entity:Ghoul x 4
	Wave 5 - entity:Skeleton_Archmage x 3 + entity:Large_Aberrant_Zombie x 3 + entity:Wraith x 2
}

enum ShadowKnightCitadel <<Dungeon / Cost : 22 / Reward : 72>> {
	Wave 1 - entity:Skeleton_Horse x 3 + entity:Undead_Pig x 4 + entity:Undead_Chicken x 5
	Wave 2 - entity:Armored_Skeleton_Horse x 3 + entity:Skeleton_Knight x 4
	Wave 3 - entity:Wraith x 4 + entity:Skeleton_Archmage x 3
	Wave 4 - entity:Shadow_Knight x 2 + entity:Armored_Skeleton_Horse x 3 + entity:Wraith x 3
	Wave 5 - entity:Shadow_Knight x 3 + entity:Skeleton_Archmage x 3 + entity:Armored_Skeleton_Horse x 4
}

class SpiritThreshold <<Cost : 21 / Reward : 9>> {
	Ticks : 25
	ID: entity:Root_Spirit / Weight : 2
	ID: entity:Frost_Spirit / Weight : 2
	ID: entity:Thunder_Spirit / Weight : 2
	ID: entity:Ember_Spirit / Weight : 2
	ID: entity:Earthen_Golem / Weight : 1
	ID: Ingredient_Life_Essence / Weight : 16
	ID: Ingredient_Ice_Essence / Weight : 14
	ID: Ingredient_Lightning_Essence / Weight : 14
	ID: Ingredient_Fire_Essence / Weight : 14
	ID: Ingredient_Water_Essence / Weight : 10
	ID: Ingredient_Motes_Light / Weight : 8
	ID: Ingredient_Void_Essence / Weight : 4
	ID: Ingredient_Voidheart / Weight : 1
}

class ElementalConfluence <<Cost : 24 / Reward : 11>> {
	Ticks : 25
	ID: entity:Earthen_Golem / Weight : 2
	ID: entity:Firesteel_Golem / Weight : 2
	ID: entity:Frost_Golem / Weight : 2
	ID: entity:Ember_Golem / Weight : 2
	ID: entity:Sandswept_Golem / Weight : 2
	ID: entity:Thunder_Golem / Weight : 2
	ID: entity:Frost_Spirit / Weight : 2
	ID: entity:Thunder_Spirit / Weight : 2
	ID: entity:Root_Spirit / Weight : 2
	ID: entity:Ember_Spirit / Weight : 2
	ID: Ingredient_Fire_Essence / Weight : 16
	ID: Ingredient_Ice_Essence / Weight : 16
	ID: Ingredient_Life_Essence / Weight : 16
	ID: Ingredient_Lightning_Essence / Weight : 16
	ID: Ingredient_Water_Essence / Weight : 12
	ID: Ingredient_Motes_Light / Weight : 10
	ID: Ingredient_Void_Essence / Weight : 6
	ID: Ingredient_Voidheart / Weight : 2
}

enum SpiritRealmTrial <<Dungeon / Cost : 27 / Reward : 95>> {
	Wave 1 - entity:Root_Spirit x 4 + entity:Ember_Spirit x 4
	Wave 2 - entity:Frost_Spirit x 4 + entity:Thunder_Spirit x 4
	Wave 3 - entity:Earthen_Golem x 2 + entity:Sandswept_Golem x 2 + entity:Root_Spirit x 3
	Wave 4 - entity:Ember_Golem x 2 + entity:Firesteel_Golem x 2 + entity:Ember_Spirit x 3
	Wave 5 - entity:Frost_Golem x 3 + entity:Frost_Spirit x 4
	Wave 6 - entity:Thunder_Golem x 3 + entity:Thunder_Spirit x 4
	Wave 7 - entity:Firesteel_Golem x 2 + entity:Frost_Golem x 2 + entity:Thunder_Golem x 2 + entity:Ember_Golem x 2
	Wave 8 - entity:Earthen_Golem x 2 + entity:Sandswept_Golem x 2 + entity:Firesteel_Golem x 2 + entity:Thunder_Golem x 2
}

' ─────────────────────────────────────────────
' ROOT
' ─────────────────────────────────────────────

Default --> CaveEntry : Rubble_Stone * 3
Default --> ForestEdge : Ingredient_Stick * 3
Default --> Plain : Ingredient_Fibre * 3


' ─────────────────────────────────────────────
' CAVE BRANCH
' ─────────────────────────────────────────────

CaveEntry --> Cave : Rock_Stone * 4 + Rubble_Stone * 4
Cave --> RatCave : entity:Rat * 3
Cave --> LowerCave : Rubble_Stone * 8 + entity:Bat * 1

LowerCave --> CopperCave : Ore_Copper * 2 + Rock_Stone * 12
CopperCave --> GobelinGank : Ore_Copper * 8 + Ore_Iron * 1

GobelinGank --> IronCave : Ore_Iron * 3 + Ore_Copper * 12
GobelinGank --> SandCave : Rubble_Stone * 16 + Rock_Stone * 8

IronCave --> GoldCave : Ore_Iron * 8 + Rock_Basalt * 8
IronCave --> ThoriumCave : Ore_Iron * 12 + Ore_Thorium * 1

ThoriumCave --> GobelinInvasion : Ore_Thorium * 8 + Ore_Cobalt * 1
ThoriumCave --> SilverCave : Ore_Thorium * 6 + Rock_Basalt * 12

GobelinInvasion --> CobaltCave : Ore_Thorium * 12 + Ore_Cobalt * 3

CobaltCave --> AdamantiteCave : Ore_Cobalt * 8 + Ore_Adamantite * 1
CobaltCave --> GemCave : Ore_Cobalt * 4 + Rock_Shale * 12
CobaltCave --> FireCave : Ore_Cobalt * 6 + Ore_Thorium * 6

AdamantiteCave --> GemDeepCave : Ore_Adamantite * 6 + Rock_Gem_Emerald * 2
AdamantiteCave --> MithrilCave : Ore_Adamantite * 8 + Ore_Mithril * 1

MithrilCave --> OnyxiumCave : Ore_Mithril * 8 + Ore_Onyxium * 1
OnyxiumCave --> PrismaCave : Ore_Onyxium * 8 + Ore_Prisma * 1

SandCave --> SandCavern : Block_Sand * 12 + Rock_Sandstone * 8
SandCavern --> Desert : Rock_Sandstone * 12 + Rubble_Sandstone * 6


' ─────────────────────────────────────────────
' FOREST / WATER BRANCH
' ─────────────────────────────────────────────

ForestEdge --> ForestEntry : Wood_Oak_Trunk * 4 + Ingredient_Stick * 8

ForestEntry --> Pond : Wood_Beech_Trunk * 2 + Ingredient_Stick * 6
Pond --> River : Wood_Oak_Trunk * 4 + Soil_Dirt * 12

River --> Lake : Plant_Crop_Corn_Item * 8 + Wood_Oak_Trunk * 4
River --> Sea : Wood_Beech_Trunk * 6 + Rock_Stone * 8
Sea --> PirateShipwreck : Rock_Aqua_Brick * 12 + Rock_Gem_Sapphire * 2
River --> Costline : Block_Sand * 8 + Wood_Oak_Trunk * 4

Costline --> SeaCavern : Rock_Sandstone * 8 + Ore_Copper * 2
SeaCavern --> SeaInfestedNest : Ore_Iron * 4 + Rock_Gem_Sapphire * 2
SeaInfestedNest --> SeaMonster : Ore_Cobalt * 4 + Ore_Silver * 4

ForestEntry --> Forest : Wood_Oak_Trunk * 8 + Plant_Sapling_Oak * 2

Forest --> AridForest : Wood_Ash_Trunk * 4 + Rock_Sandstone * 8
Forest --> Swamp : Plant_Crop_Mushroom_Common_Brown * 4 + Soil_Dirt * 16
Forest --> DeepForest : Wood_Beech_Trunk * 12 + Wood_Ash_Trunk * 8

Swamp --> EnchantedForest : Rock_Gem_Emerald * 2 + Plant_Sapling_Beech * 4
EnchantedForest --> FairyPond : Rock_Gem_Topaz * 2 + Plant_Crop_Mushroom_Shelve_Brown * 4

AridForest --> Desert : Wood_Ash_Trunk * 8 + Rock_Sandstone * 12

DeepForest --> DarkForest : Rock_Gem_Emerald * 4 + Wood_Oak_Trunk * 16
DarkForest --> BurnedForest : Ore_Thorium * 4 + Wood_Ash_Trunk * 12
DarkForest --> CursedForest : Rock_Gem_Topaz * 4 + Ore_Silver * 4

CursedForest --> OutlanderForest : Ore_Cobalt * 4 + Plant_Crop_Mushroom_Shelve_Brown * 6

OutlanderForest --> OutlanderGank : Ore_Cobalt * 6 + Wood_Ash_Trunk * 12
OutlanderForest --> OutlanderPlain : Plant_Crop_Wheat_Item * 16 + entity:Sheep * 2

OutlanderPlain --> OutlanderCity : Ore_Adamantite * 4 + Plant_Crop_Corn_Item * 16
OutlanderPlain --> Toundra : Ore_Silver * 6 + Rock_Gem_Sapphire * 2

Toundra --> FrozenForest : Rock_Ice * 8 + Wood_Ice_Trunk * 4
Toundra --> IceLand : Rock_Ice * 12 + Rubble_Ice * 8


' ─────────────────────────────────────────────
' FROZEN BRANCH
' ─────────────────────────────────────────────

IceLand --> IcyCavern : Rubble_Ice * 12 + Ore_Silver * 4
IcyCavern --> YetiCavern : Ingredient_Ice_Essence * 4 + Ore_Cobalt * 4
YetiCavern --> IceTemple : Ore_Adamantite * 4 + Rock_Gem_Diamond * 2

FrozenForest --> IcyForest : Wood_Ice_Trunk * 8 + Rock_Ice * 8

IcyCavern --> FrozenGraveyard : Ingredient_Bone_Fragment * 16 + Rock_Ice * 12
FrozenGraveyard --> IcyNecropolis : Ingredient_Ice_Essence * 4 + Deco_Bone_Full * 8
IcyNecropolis --> FrostboneCrypt : Rock_Gem_Sapphire * 4 + Ingredient_Ice_Essence * 8
FrostboneCrypt --> IceTemple : Rock_Gem_Diamond * 2 + Ingredient_Ice_Essence * 10

' ─────────────────────────────────────────────
' FIRE / HELL BRANCH
' ─────────────────────────────────────────────

BurnedForest --> FireLand : Ore_Cobalt * 8 + Ore_Thorium * 8

FireLand --> Volcano : Ore_Adamantite * 4 + Rock_Volcanic * 8
FireLand --> FieryGraveward : Ore_Thorium * 12 + Rock_Basalt * 16

FieryGraveward --> FireCave : Ore_Cobalt * 8 + Rock_Basalt * 24

FireCave --> HellGate : Ore_Adamantite * 8 + Rock_Volcanic * 12
HellGate --> HellPlain : Ore_Mithril * 6 + Ore_Onyxium * 1
HellGate --> HellSwamp : Ore_Mithril * 4 + Rock_Gem_Ruby * 4

HellPlain --> FireGemCave : Ore_Onyxium * 4 + Ore_Prisma * 1

FieryGraveward --> BurntBattlefield : Ingredient_Bone_Fragment * 18 + Rock_Volcanic * 12
BurntBattlefield --> AshenCatacombs : Ingredient_Fire_Essence * 6 + Deco_Bone_Full * 8
AshenCatacombs --> BurntSkeletonCitadel : Rock_Gem_Ruby * 4 + Ingredient_Fire_Essence * 10
BurntSkeletonCitadel --> HellGate : Ore_Mithril * 4 + Rock_Volcanic_Cracked_Incandescent * 12


' ─────────────────────────────────────────────
' JUNGLE BRANCH
' ─────────────────────────────────────────────
Forest --> JungleEdge : Wood_Beech_Trunk * 12 + Plant_Moss_Block_Green * 8
DeepForest --> JungleEdge : Wood_Maple_Trunk * 8 + Plant_Leaves_Bramble * 8
JungleEdge --> OvergrownRuins : Plant_Moss_Block_Green * 12 + Rock_Gem_Emerald * 2

Desert --> DryJunglePass : Rock_Sandstone * 16 + Plant_Cactus_1 * 6
InnerDesert --> DryJunglePass : Block_Sand * 20 + Plant_Cactus_Flat_1 * 6
DryJunglePass --> SunkenJungleRuins : Rock_Sandstone_Brick * 8 + Soil_Clay_Blue * 12

OvergrownRuins --> JungleCrypt : Ingredient_Bone_Fragment * 12 + Rock_Runic_Brick * 8
SunkenJungleRuins --> JungleCrypt : Ingredient_Bone_Fragment * 12 + Rock_Sandstone_Brick * 12

JungleCrypt --> LostNecropolis : Deco_Bone_Full * 8 + Rock_Gem_Emerald * 3
LostNecropolis --> AncientUndeadSanctum : Rock_Gem_Ruby * 3 + Rock_Runic_Brick_Ornate * 10

LostNecropolis --> ShadowedJungleRoad : Rock_Gem_Zephyr * 2 + Deco_Bone_Spine * 8
ShadowedJungleRoad --> ArmoredDeadGrove : Rock_Runic_Brick_Ornate * 10 + Ingredient_Bone_Fragment * 20
ArmoredDeadGrove --> ShadowKnightCitadel : Rock_Gem_Zephyr * 4 + Deco_Bone_Spine * 12


' ─────────────────────────────────────────────
' DESERT / TEMPLE / INSECT BRANCH
' ─────────────────────────────────────────────

Desert --> DesertTempleEntrace : Plant_Cactus_1 * 4 + Rock_Sandstone * 12

DesertTempleEntrace --> DeeperDesertTemple : Rock_Sandstone * 24 + Ore_Gold * 4
DeeperDesertTemple --> DesertTemple : Ore_Gold * 8 + Rock_Gem_Topaz * 2
DesertTemple --> PharaonRoom : Ore_Gold * 12 + Rock_Gem_Diamond * 1

Desert --> InnerDesert : Plant_Cactus_Flat_1 * 4 + Block_Sand * 24
InnerDesert --> InsectInvasion : Plant_Cactus_Ball_1 * 6 + Rock_Sandstone * 16

InsectInvasion --> MuddyDesert : Soil_Dirt * 32 + Block_Sand * 16
MuddyDesert --> InfestedDesert : Plant_Cactus_1 * 8 + Plant_Crop_Carrot_Item * 12

InfestedDesert --> InsectNest : Ore_Iron * 8 + Plant_Cactus_Ball_1 * 8
InsectNest --> InsideInsectNest : Ore_Cobalt * 6 + Rock_Gem_Ruby * 2
InsideInsectNest --> InsectCore : Ore_Adamantite * 6 + Rock_Gem_Emerald * 4

' ─────────────────────────────────────────────
' PLAINS / HALLOW / QUARRY BRANCH
' ─────────────────────────────────────────────

Plain --> Quarry : Rubble_Stone * 12 + Rock_Stone * 8
Plain --> Hallow : Plant_Crop_Wheat_Item * 12 + entity:Sheep * 2

Hallow --> CowHallow : Plant_Crop_Wheat_Item * 16 + Plant_Crop_Corn_Item * 8
Hallow --> HorseHallow : Plant_Crop_Carrot_Item * 16 + Plant_Crop_Wheat_Item * 8
Hallow --> River : Plant_Crop_Corn_Item * 8 + Wood_Oak_Trunk * 4


' ─────────────────────────────────────────────
' CURSED / UNDEAD / VOID BRANCH
' ─────────────────────────────────────────────

CursedForest --> Graveyard : Ore_Silver * 8 + Rock_Shale * 16
Graveyard --> UndeadTemple : Ore_Gold * 6 + Rock_Gem_Diamond * 1

UndeadTemple --> VoidPortal : Ore_Onyxium * 4 + Rock_Gem_Zephyr * 2
VoidPortal --> VoidTemple : Ore_Prisma * 4 + Rock_Gem_Zephyr * 4


FireGemCave --> ElementalConfluence
IcyForest --> SpiritThreshold

VoidPortal --> SpiritThreshold : Rock_Gem_Zephyr * 3 + Ingredient_Fire_Essence * 4 + Ingredient_Ice_Essence * 4
SpiritThreshold --> ElementalConfluence : Ingredient_Life_Essence * 6 + Ingredient_Lightning_Essence * 6
ElementalConfluence --> SpiritRealmTrial : Ingredient_Void_Essence * 6 + Ingredient_Motes_Light * 12


' ─────────────────────────────────────────────
' MYSTERY / DINOSAUR BRANCH
' ─────────────────────────────────────────────

Quarry --> MysteriousCavern : Rock_Stone * 24 + Ore_Copper * 4
MysteriousCavern --> MysticCave : Rock_Gem_Sapphire * 2 + Ore_Iron * 8

MysticCave --> LuxirousCave : Rock_Gem_Emerald * 4 + Ore_Gold * 8
LuxirousCave --> JurassicCave : Rock_Gem_Diamond * 2 + Ore_Adamantite * 8
JurassicCave --> DinoCrisis : Ingredient_Hide_Scaled * 12 + Rock_Gem_Diamond * 2 + Ore_Adamantite * 8

' ─────────────────────────────────────────────
' TRORK BRANCH
' ─────────────────────────────────────────────

DeepForest --> TrorkHuntingGround : Wood_Beech_Trunk * 12 + Plant_Leaves_Bramble * 8
TrorkHuntingGround --> TrorkWarband : Ingredient_Hide_Scaled * 6 + Wood_Ash_Trunk * 16

Desert --> DryTrorkCamp : Rock_Sandstone * 16 + Plant_Cactus_1 * 6
DryTrorkCamp --> TrorkWarband : Ingredient_Hide_Scaled * 6 + Rock_Sandstone * 24

TrorkWarband --> TrorkStrongholdApproach : Ingredient_Leather_Scaled * 6 + Ore_Thorium * 4
TrorkStrongholdApproach --> TrorkElderGrove : Rock_Gem_Emerald * 4 + Wood_Amber_Trunk * 8
TrorkElderGrove --> TrorkChieftainCamp : Rock_Gem_Zephyr * 2 + Ingredient_Leather_Scaled * 10 + Ore_Cobalt * 4

@enduml